# Import Format

In [1]:
import numpy as np

# Numpy array formats

In [2]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
b = np.array([[1,2,3,4,5], [6,7,8,9,10]])
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [4]:
b_2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
b_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
c = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [6]:
d = np.zeros(10)
d

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
d_1 = np.zeros((5,5))
d_1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
d_2 = np.zeros((2,2,2))
d_2

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [9]:
e = np.ones(10)
e

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
e_1 = np.ones((5,5))
e_1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
e_2 = np.ones((3,3,3))
e_2

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [12]:
f = np.empty(10)
f

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
f_1 = np.empty((5,5))
f_1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
f_2 = np.empty((3,3,3))
f_2

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [15]:
g = np.full(10, 11)
g

array([11, 11, 11, 11, 11, 11, 11, 11, 11, 11])

In [16]:
g_1 =  np.full((4,4), 14)
g_1

array([[14, 14, 14, 14],
       [14, 14, 14, 14],
       [14, 14, 14, 14],
       [14, 14, 14, 14]])

In [17]:
g_2 = np.full((2,2,2), 100)
g_2

array([[[100, 100],
        [100, 100]],

       [[100, 100],
        [100, 100]]])

In [18]:
arr = [1,2,3,4,5]
h = np.array(arr)
h

array([1, 2, 3, 4, 5])

In [19]:
i = np.linspace(2, 20, 10)
i

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [20]:
i_1 = np.linspace(5, 10, 20)
i_1

array([ 5.        ,  5.26315789,  5.52631579,  5.78947368,  6.05263158,
        6.31578947,  6.57894737,  6.84210526,  7.10526316,  7.36842105,
        7.63157895,  7.89473684,  8.15789474,  8.42105263,  8.68421053,
        8.94736842,  9.21052632,  9.47368421,  9.73684211, 10.        ])

In [21]:
rng = np.arange(10)
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
rng_1 = np.arange(101)
rng_1

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [23]:
j = np.zeros_like(e_2)
j

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [24]:
j_1 = np.ones_like(j)
j_1

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

# Numpy array Attributes

In [25]:
a = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15], [16,17,18,19,20]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [26]:
a.size

20

In [27]:
a.shape

(4, 5)

In [28]:
a.itemsize

4

In [29]:
a.ndim

2

In [30]:
a.dtype

dtype('int32')

In [31]:
a.nbytes

80

# Data Types
# Int (8,16,32,64 bytes)
# uint (8,16,32,64 bytes)
# Float (16, 32, 64, 128 bytes)
# Complex (64, 128, 256 bytes)
# Other Tyes (Objects, Bool, Bytes, numpy.void, String)

In [32]:
import pprint as pp
pp.pprint(np.sctypes)

{'complex': [<class 'numpy.complex64'>, <class 'numpy.complex128'>],
 'float': [<class 'numpy.float16'>,
           <class 'numpy.float32'>,
           <class 'numpy.float64'>],
 'int': [<class 'numpy.int8'>,
         <class 'numpy.int16'>,
         <class 'numpy.int32'>,
         <class 'numpy.int64'>],
 'others': [<class 'bool'>,
            <class 'object'>,
            <class 'bytes'>,
            <class 'str'>,
            <class 'numpy.void'>],
 'uint': [<class 'numpy.uint8'>,
          <class 'numpy.uint16'>,
          <class 'numpy.uint32'>,
          <class 'numpy.uint64'>]}


# Examples

In [33]:
a = np.array([1,2,3,4,5], dtype=np.int16)
print(a.dtype)
a

int16


array([1, 2, 3, 4, 5], dtype=int16)

In [34]:
b = np.array([1,2,3,4,5], dtype=np.complex64)
print(b.dtype)
b

complex64


array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j], dtype=complex64)

In [35]:
c = np.array([1,2,3,4,5], dtype=np.uint32)
print(c.dtype)
c

uint32


array([1, 2, 3, 4, 5], dtype=uint32)

In [36]:
d = np.array([1,2,3,4,5], dtype=np.float16)
print(d.dtype)
d

float16


array([1., 2., 3., 4., 5.], dtype=float16)

# Mathematical Functions

In [37]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
b = np.array([[2,4,6,8], [10,12,14,16], [18,20,22,24], [26,28,30,32]])

print(a)
b

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [38]:
a+b

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36],
       [39, 42, 45, 48]])

In [39]:
b-a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [40]:
a*b

array([[  2,   8,  18,  32],
       [ 50,  72,  98, 128],
       [162, 200, 242, 288],
       [338, 392, 450, 512]])

In [41]:
b/a

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [42]:
a>10

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [43]:
b<15

array([[ True,  True,  True,  True],
       [ True,  True,  True, False],
       [False, False, False, False],
       [False, False, False, False]])

In [44]:
a[a<=5]

array([1, 2, 3, 4, 5])

In [45]:
b[b>=20]

array([20, 22, 24, 26, 28, 30, 32])

In [46]:
b.min()

2

In [47]:
b.max()

32

In [48]:
a.sum()

136

In [49]:
a.mean()

8.5

In [50]:
a.var()

21.25

In [51]:
a.std()

4.6097722286464435

In [52]:
a.dot(b)

array([[ 180,  200,  220,  240],
       [ 404,  456,  508,  560],
       [ 628,  712,  796,  880],
       [ 852,  968, 1084, 1200]])

In [53]:
b.sum(axis=0)

array([56, 64, 72, 80])

In [54]:
b.sum(axis=1)

array([ 20,  52,  84, 116])

In [55]:
b.argmin()

0

In [56]:
b.argmax()

15

In [57]:
b.argsort()

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]], dtype=int64)

# Strings in numpy

# Operation format = np.char.#operation(#np string array)

In [58]:
a = np.char.add(['hello ', 'good'], ['world', 'morning'])
a

array(['hello world', 'goodmorning'], dtype='<U13')

In [59]:
b = np.char.multiply('yeeha', 5)
b

array('yeehayeehayeehayeehayeeha', dtype='<U25')

In [60]:
c = np.char.center('Hello World', 40)
c

array('              Hello World               ', dtype='<U40')

In [61]:
c_1 = np.char.center('Hello World', 40, fillchar='$')
c_1

array('$$$$$$$$$$$$$$Hello World$$$$$$$$$$$$$$$', dtype='<U40')

In [62]:
d = np.char.capitalize('hello world')
d

array('Hello world', dtype='<U11')

In [63]:
e = np.char.title('the boy is going home')
e

array('The Boy Is Going Home', dtype='<U21')

In [64]:
f = np.char.lower(['THIS', 'IS', 'AWESOME'])
f

array(['this', 'is', 'awesome'], dtype='<U7')

In [65]:
g = np.char.upper(['this', 'is', 'awesome'])
g

array(['THIS', 'IS', 'AWESOME'], dtype='<U7')

In [66]:
h = np.char.split('The boy is going home')
h

array(list(['The', 'boy', 'is', 'going', 'home']), dtype=object)

In [67]:
i = np.char.splitlines('The boy \n is going \n home')
i

array(list(['The boy ', ' is going ', ' home']), dtype=object)

In [68]:
j = np.char.strip(['airplane', 'anita', 'alaska'], 'a')
j

array(['irplane', 'nit', 'lask'], dtype='<U8')

In [69]:
k = np.char.join(['dmy', 'hms'], ['-', ':'])
k

array(['-', ':'], dtype='<U1')

In [70]:
k_2 = np.char.replace('The boy is going home', 'home', 'somewhere else')
k_2

array('The boy is going somewhere else', dtype='<U31')

# Other Numpy Functions 

In [71]:
a = np.arange(15)
a_1 = a.reshape(5,3)
a_1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [72]:
b = np.arange(100)
b_1 = b.reshape(2,50)
b_1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [73]:
c = a_1.flatten()
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [74]:
c_1 = a_1.flatten(order='F')
c_1

array([ 0,  3,  6,  9, 12,  1,  4,  7, 10, 13,  2,  5,  8, 11, 14])

In [75]:
c_2 = a_1.flatten(order="C")
c_2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [76]:
print(a_1)
d = np.transpose(a_1)
d

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [77]:
print(b_1)
d_1 = np.transpose(b_1)
d_1

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
  48 49]
 [50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
  74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
  98 99]]


array([[ 0, 50],
       [ 1, 51],
       [ 2, 52],
       [ 3, 53],
       [ 4, 54],
       [ 5, 55],
       [ 6, 56],
       [ 7, 57],
       [ 8, 58],
       [ 9, 59],
       [10, 60],
       [11, 61],
       [12, 62],
       [13, 63],
       [14, 64],
       [15, 65],
       [16, 66],
       [17, 67],
       [18, 68],
       [19, 69],
       [20, 70],
       [21, 71],
       [22, 72],
       [23, 73],
       [24, 74],
       [25, 75],
       [26, 76],
       [27, 77],
       [28, 78],
       [29, 79],
       [30, 80],
       [31, 81],
       [32, 82],
       [33, 83],
       [34, 84],
       [35, 85],
       [36, 86],
       [37, 87],
       [38, 88],
       [39, 89],
       [40, 90],
       [41, 91],
       [42, 92],
       [43, 93],
       [44, 94],
       [45, 95],
       [46, 96],
       [47, 97],
       [48, 98],
       [49, 99]])

In [78]:
print(a_1)
e = np.rollaxis(a_1, 0)
e

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [79]:
print(a_1)
e_1 = np.rollaxis(a_1, 1)
e_1

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [80]:
print(a_1)
f = np.swapaxes(a_1, 0,0)
f

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [81]:
print(a_1)
f_1 = np.swapaxes(a_1, 0,1)
f_1

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [82]:
#Indexing
a = np.arange(10)
print(a)
print(a[0])
print(a[5])
print(a[-1])
print(a[-2])

[0 1 2 3 4 5 6 7 8 9]
0
5
9
8


In [83]:
print(a[:5])
print(a[5:])
print(a[1:4])
print(a[:-2])

[0 1 2 3 4]
[5 6 7 8 9]
[1 2 3]
[0 1 2 3 4 5 6 7]


In [84]:
a = np.arange(15).reshape(5,3)
print(a)

for item in np.nditer(a, order='C'):
    print(item)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [85]:
for item in np.nditer(a, order='F'):
    print(item)

0
3
6
9
12
1
4
7
10
13
2
5
8
11
14


In [86]:
a = np.arange(8).reshape(2,2,2)
print(a)

a.flatten()

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


array([0, 1, 2, 3, 4, 5, 6, 7])

In [87]:
b = np.arange(12).reshape(3,4)
print(b)

c = np.arange(80,92).reshape(3,4)
c

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[80, 81, 82, 83],
       [84, 85, 86, 87],
       [88, 89, 90, 91]])

In [88]:
np.concatenate((b,c))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [80, 81, 82, 83],
       [84, 85, 86, 87],
       [88, 89, 90, 91]])

In [89]:
np.concatenate((b,c), axis=1)

array([[ 0,  1,  2,  3, 80, 81, 82, 83],
       [ 4,  5,  6,  7, 84, 85, 86, 87],
       [ 8,  9, 10, 11, 88, 89, 90, 91]])

In [90]:
d = np.arange(15)
np.split(d, 3)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]

In [91]:
np.split(d, (3,6,9))

[array([0, 1, 2]),
 array([3, 4, 5]),
 array([6, 7, 8]),
 array([ 9, 10, 11, 12, 13, 14])]

In [92]:
np.split(d, (2,4,7,10,12))

[array([0, 1]),
 array([2, 3]),
 array([4, 5, 6]),
 array([7, 8, 9]),
 array([10, 11]),
 array([12, 13, 14])]

In [93]:
print(d)
e = np.resize(d, (4,4))
e

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14,  0]])

In [94]:
print(d)
e_1 = np.resize(d, (5,5))
e_1

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])